/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    celehead: THREE.Mesh;
  };
  materials: {
    ["kt_facebuilder_material.005"]: THREE.MeshStandardMaterial;
  };
};

const Model = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/celestin.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.celehead.geometry}
        material={materials["kt_facebuilder_material.005"]}
      />
    </group>
  );
}

useGLTF.preload("/celestin.glb");

export default Model