/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    celehead: THREE.Mesh;
  };
  materials: {
    defaultMaterial: THREE.MeshStandardMaterial;
  };
};

export function ModelSimple(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/celestin.gltf") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.celehead.geometry}
        material={materials.defaultMaterial}
      />
    </group>
  );
}

useGLTF.preload("/celestin.gltf");

export default ModelSimple